name: threestudio_o3d
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch==2.4.1
  - torchvision==0.19.1
  - torchaudio==2.4.1
  - pytorch-cuda=11.8
  - numpy
  - pip:
      - lightning==2.0.0
      - omegaconf==2.3.0
      - jaxtyping
      - typeguard
      - git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2
      - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
      - diffusers<0.20
      - transformers==4.28.1
      - accelerate
      - opencv-python
      - tensorboard
      - matplotlib
      - imageio>=2.28.0
      - imageio[ffmpeg]
      - git+https://github.com/NVlabs/nvdiffrast.git
      - libigl
      - xatlas
      - trimesh[easy]
      - networkx
      - pysdf
      - PyMCubes
      - wandb
      - gradio==4.11.0
      - git+https://github.com/ashawkey/envlight.git
      - torchmetrics
      - IPython
      - ipywidgets

      # deepfloyd
      - xformers
      - bitsandbytes==0.38.1
      - sentencepiece
      - safetensors
      - huggingface_hub<0.26.0

      # for zero123
      - einops
      - kornia
      - taming-transformers-rom1504
      - git+https://github.com/openai/CLIP.git

      #controlnet
      - controlnet_aux
      
      - git+https://github.com/threestudio-project/threestudio.git